### ISSUE TITLE
[General question] [TT] [MCPC+] Twilight Forest issues 

### ISSUE THREAD

**Issue by alicheek** [MinimallyCorrect/TickThreading#492]
hey I don't know if im the only one so that's why im asking, now ive just checked just to make sure its not multiverse core and its not but, if any one goes into the TF to mine or kill mobs it seems to be randomly laggy; for instance when some one is mining away with a mining laser they wont be able to pick up all the items on the ground, some will just stay there almost like its not registering the player is ontop of it, the same idea is happening with the mobs too they seem to not notice any interactions with players, like hitting them

Just would be interesting to see if any one else has this issue 

Cheers

**Comment by NachtRaben** [comment]
using mcpc+ L25 and most recent tick threading without multiverse and i have no issues

**Comment by alicheek** [comment]
weird with mine I do maybe its my mod pack that's gone a bit iffy, weird but it could be possible, I mean ive tried making new twilight forest maps too but the same thing happens

**Comment by LunNova** [comment]
If a player experiencing this problem relogs does it start working?

**Comment by alicheek** [comment]
not sure ill give it a try but my server has locked down its been doing this very often lately even with the new TT builds and L27 of MCPC where I cant even access the server through ssh or ftp

**Comment by NachtRaben** [comment]
I've never seen this issue before... I'll try and recreate it. can you run some profiles while ur in the twilight? see how the server is handling it when u can get back in?

**Comment by alicheek** [comment]
ive tried doing profiles can some one please explain how to do it , couldn't even find the java file to use to run it lol

**Comment by Shybella** [comment]
Small problem. I'm using MCPC+ build L28 and running Yogcraft. Both aggressive and passive mobs seem to react slowly sometimes ignoring the player completely. This also seems to affect floating entities.

**Comment by alicheek** [comment]
yea that's exactly my problem

**Comment by alicheek** [comment]
Here is some pictures showing , at the TF's frozen point; you can see that I can cut down the log blocks fine, but they don't stack together on the ground and I cant pick them up, when it is in this state all mobs are frozen and don't take damage, it will maybe stay in this state for about 2 mins then for a short period it will work, in the short period of it working the player is able to pick up all the items and damage mobs, when it is in this state the items on the ground also now stack together.

![2013-05-15_14 03 48](https://f.cloud.github.com/assets/3965516/506855/22efd45c-bd61-11e2-9d81-1faed86af968.png)
![2013-05-15_14 06 36](https://f.cloud.github.com/assets/3965516/506857/2485b1d8-bd61-11e2-99df-09ad49ff91ac.png)

**Comment by Shybella** [comment]
Yeap, that's it. Having the same exact problem.

**Comment by Shybella** [comment]
What can I do to provide you as much information as possible?

**Comment by LunNova** [comment]
When it unfreezes, does a user also login or enter/leave the TF?

**Comment by Shybella** [comment]
This is happening for me in all worlds. Relogging has a 50% chance to help

**Comment by Shybella** [comment]
Ok, if the user teleports to spawn and does /back they're able to pick up the item.. Also i changed the target ticks to 18 from 20 and it seemed to improve mob AI

**Comment by Shybella** [comment]
It's almost like the chunk becomes unloaded while the user is there, when they teleport away and come back it reloads it..

**Comment by alicheek** [comment]
Found the issue guys its MCPC+ Bukkit configs, make sure if you have your TF set in the world settings, give it all the parameters like the mob spawning range the growth chunks the item merge range and take out the view distance setting in it also I put in all the growth modifiers which are in the default settings.

**Comment by LunNova** [comment]
It may be a more serious issue corrupting the tickRegions list, which could
cause many of the issues you have reported today.

**Comment by alicheek** [comment]
Your right it may be linked but after me doing that the TF is now working perfectly

**Comment by Shybella** [comment]
Still happening for me in all worlds

**Comment by alicheek** [comment]
do you use MCPC?

**Comment by Shybella** [comment]
Yeap, MCPC+ L28 Build.

**Comment by alicheek** [comment]
ok does ur bukkit config look something like  this for the world-settings: ?

```
world-settings:
  default:
    growth-chunks-per-tick: 0
    mob-spawn-range: 4
    item-merge-radius: 3.5
    exp-merge-radius: 3.5
    random-light-updates: true
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    verbose: false
  world:
    growth-chunks-per-tick: 0
    mob-spawn-range: 4
    item-merge-radius: 3.5
    exp-merge-radius: 3.5
    random-light-updates: true
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    verbose: false
  world_nether:
    view-distance: 4
    growth-chunks-per-tick: 0
    random-light-updates: false
    water-creatures-per-chunk: 0
  overworld_nether:
    growth-chunks-per-tick: 0
    mob-spawn-range: 4
    item-merge-radius: 3.5
    exp-merge-radius: 3.5
    random-light-updates: false
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    verbose: false
    water-creatures-per-chunk: 0
  overworld:
    growth-chunks-per-tick: 750
    mob-spawn-range: 4
    item-merge-radius: 3.5
    exp-merge-radius: 3.5
    random-light-updates: false
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    verbose: false
  World_VIP:
    growth-chunks-per-tick: 550
    mob-spawn-range: 4
    item-merge-radius: 3.5
    exp-merge-radius: 3.5
    random-light-updates: false
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    verbose: false
  world_twilightforest:
    growth-chunks-per-tick: 400
    mob-spawn-range: 4
    exp-merge-radius: 3.5
    aggregate-chunkticks: 4
    wheat-growth-modifier: 100
    cactus-growth-modifier: 100
    melon-growth-modifier: 100
    pumpkin-growth-modifier: 100
    sugar-growth-modifier: 100
    tree-growth-modifier: 100
    mushroom-growth-modifier: 100
    random-light-updates: false
    water-creatures-per-chunk: 0
    verbose: false
```
